care_and_share/care_and_share/urls.py
from django.contrib import admin
from django.urls import path
from main_app.views import LandingPage, AddDonation, Login, Register, Logout, UserDetails, Confirmation, UserDetailsUpdate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', LandingPage.as_view(), name='LandingPage' ),
    path('share/', AddDonation.as_view(), name='AddDonation'),
    path('login/', Login.as_view(), name='Login'),
    path('register/', Register.as_view(), name='Register'),
    path('logout/', Logout.as_view(), name='Logout'),
    path('user_details/<int:pk>/', UserDetails.as_view(), name='User Details'),
    path('confirmation/', Confirmation.as_view(), name='Confirmation'),
    path('user_update/<int:pk>/', UserDetailsUpdate.as_view(), name='User Details Update'),
]

care_and_share/accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone

from accounts.managers import CustomUserManager

# można nazwać po prostu "user"
# można dziedziczyć z AbstractUser i np username = None
class CustomUser(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=64, verbose_name='Imię')
    surname = models.CharField(max_length=64, verbose_name='Nazwisko')
    email = models.EmailField(max_length=64, unique=True, verbose_name='Email')
    password = models.CharField(max_length=64, verbose_name='Hasło')
    password_2 = models.CharField(max_length=64, verbose_name='Powtórz hasło')
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()
    # UserManager

    def __str__(self):
        return self.email

# class User(AbstractUser, PermissionsMixin):
#         username = None
#         email = models.EmailField(max_length=64, unique=True)
#         password_2 = models.CharField(max_length=64)
#
#         USERNAME_FIELD = 'email'
#         REQUIRED_FIELDS = []
#
#         objects = UserManager()

care_and_share/main_app/models.py
from django.contrib.auth.models import User
from django.db import models

from accounts.models import CustomUser


class Category(models.Model):
    name = models.CharField(max_length=64)


types = (
    (0, 'Fundacja'),
    (1, 'Organizacja pozarządowa'),
    (2, 'Zbiórka lokalna'),
)


class Institution(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField()
    type = models.IntegerField(choices=types, default=0)
    categories = models.ManyToManyField(Category)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return f'{self.get_type_display()}: {self.name}. Opis: {self.description}'


class Donation(models.Model):
    quantity = models.IntegerField()
    categories = models.ManyToManyField(Category)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    address = models.TextField()
    phone_number = models.IntegerField()
    city = models.CharField(max_length=64)
    zip_code = models.TextField(max_length=6)
    pick_up_date = models.DateField()
    pick_up_time = models.TimeField(null=True)
    pick_up_comment = models.TextField()
    user = models.ForeignKey(CustomUser, null=True, on_delete=models.CASCADE)

care_and_share/accounts/forms.py
from django import forms

from accounts.models import CustomUser


class CustomUser(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'surname', 'email']

care_and_share/accounts/views.py
from django.shortcuts import render

# Create your views here.

care_and_share/accounts/templates/accounts/customuser_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container--90">
<h1> Witaj {{ user.first_name }} !</h1>
    <h1> Oto Twoje dane:</h1>
    <h1> Numer użytkownika: {{ user.pk }}</h1>
    <h1> Imię: {{ user.first_name }}</h1>
    <h1> Nazwisko: {{ user.surname }}</h1>
    <h1> Email: {{ user.email }} </h1>
    <h1> Data utworzenia konta: {{ user.date_joined }} </h1>
    <h1> Wsparte organizacje: </h1>
    <ol>
        {% for donation in user.donation_set.all %}
            <h1><li> {{ donation.institution.get_type_display }} {{ donation.institution.name }}. <br>
                Ilość przekazanych worków: {{ donation.quantity }}. <br>
                Data odbioru: {{ donation.pick_up_date }}<br>
                Kategorie:
                {% for category in donation.categories.all %}
                    {{ category.name }},
                    {% endfor %}
            </li></h1>
        {% empty %}
       <h1> Jeszcze nie wsparłeś żadnej organizacji.</h1>
        {% endfor %}
    </ol>
</div>
{% endblock %}

care_and_share/accounts/templates/accounts/customuser_update_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="container--90">
<h1> Witaj {{ user.first_name }} !</h1>
        <h1> Czy chcesz zmienić swoje dane? </h1>
    <form action="" method="POST">
        {% csrf_token %}
        <h1> {{ form.as_p }}
        <input type="submit" value="Zatwierdź"></h1>
    </form>

</div>
{% endblock %}